version: 2.1

executors:
  cimg-base:
    docker:
      - image: cimg/base:stable
  python:
    docker:
      - image: cimg/python:3.10.7

parameters:
  build-ios:
    type: boolean
    default: false
  build-android:
    type: boolean
    default: false

jobs:
  workflow-status-check-job:
    executor: python
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python .circleci/check-workflow-status.py <<pipeline.git.revision>>
  rerun-workflow-status-check-job:
    executor: python
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python3 .circleci/rerun-workflow.py <<pipeline.git.revision>>
  ios-test-job:
    executor: cimg-base
    steps:
      - checkout
      - run: sleep 60
      - run: echo "iOS"
  android-test-job:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "Android"
workflows:
  workflow-status-checks-workflow:
    jobs:
      - workflow-status-check-job
  ios-workflow:
    when: << pipeline.parameters.build-ios >>
    jobs:
      - ios-test-job
      - rerun-workflow-status-check-job:
          requires:
            - ios-test-job
  android-workflow:
    when: << pipeline.parameters.build-android >>
    jobs:
      - android-test-job
      - rerun-workflow-status-check-job:
          requires:
            - android-test-job
